CREATE USER "ROOT1" WITH PASSWORD '939&:9:&?9********';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "ROOT1";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "ROOT1";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "ROOT1";
ALTER USER "ROOT1" WITH CREATEDB;
CREATE USER 'ROOT1'@'%' IDENTIFIED BY '939&:9:&?9********';
GRANT ALL PRIVILEGES ON *.* TO 'ROOT1'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
